# Generated by Django 5.0.2 on 2024-03-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encadrement',
            name='role_chercheur2',
            field=models.CharField(choices=[('encadreur', 'Encadreur'), ('co_encadreur', 'Co_encadreur')], default='', max_length=50),
        ),
    ]
